// Generated by Wrangler on Sat Jul 06 2024 09:16:42 GMT-0400 (Eastern Daylight Saving Time)
// by running `wrangler types`

interface Env {
	licenses: KVNamespace;
	activations: KVNamespace;
	hardwareIds: KVNamespace;
	tokens: KVNamespace;
}
